package com.mlaroche.smartheater.dao;

import javax.inject.Inject;

import io.vertigo.dynamo.impl.store.util.DAO;
import io.vertigo.dynamo.store.StoreManager;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.dynamo.task.TaskManager;
import com.mlaroche.smartheater.domain.HeaterMode;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class HeaterModeDAO extends DAO<HeaterMode, java.lang.String> implements StoreServices {

	/**
	 * Contructeur.
	 * @param storeManager Manager de persistance
	 * @param taskManager Manager de Task
	 */
	@Inject
	public HeaterModeDAO(final StoreManager storeManager, final TaskManager taskManager) {
		super(HeaterMode.class, storeManager, taskManager);
	}

}
