package com.mlaroche.smartheater.dao.heater;

import javax.inject.Inject;

import io.vertigo.core.node.Node;
import io.vertigo.core.lang.Assertion;
import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.impl.dao.StoreServices;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class HeaterPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public HeaterPAO(final TaskManager taskManager) {
		Assertion.check().isNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkGetHeatersByMode.
	 * @return DtList de HeatersByMode result
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkGetHeatersByMode",
			request = "select mod_cd as MODE,  count(mod_cd) as COUNT from heater group by mod_cd",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtHeatersByMode")
	public io.vertigo.datamodel.structure.model.DtList<com.mlaroche.smartheater.domain.HeatersByMode> getHeatersByMode() {
		final Task task = createTaskBuilder("TkGetHeatersByMode")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TkSwitchHeaterToAuto.
	 * @param heaId Long
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkSwitchHeaterToAuto",
			request = "update heater set auto = true where hea_id = #heaId#",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProc.class)
	public void switchHeaterToAuto(@io.vertigo.datamodel.task.proxy.TaskInput(name = "heaId", smartType = "STyId") final Long heaId) {
		final Task task = createTaskBuilder("TkSwitchHeaterToAuto")
				.addValue("heaId", heaId)
				.build();
		getTaskManager().execute(task);
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
