package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class ElectricalConsumption implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.time.Instant timestamp;
	private Double meanPower;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Heure'.
	 * @return Instant timestamp
	 */
	@Field(smartType = "STyTimestamp", label = "Heure")
	public java.time.Instant getTimestamp() {
		return timestamp;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Heure'.
	 * @param timestamp Instant
	 */
	public void setTimestamp(final java.time.Instant timestamp) {
		this.timestamp = timestamp;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Puissance moyenne'.
	 * @return Double meanPower
	 */
	@Field(smartType = "STyDouble", label = "Puissance moyenne")
	public Double getMeanPower() {
		return meanPower;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Puissance moyenne'.
	 * @param meanPower Double
	 */
	public void setMeanPower(final Double meanPower) {
		this.meanPower = meanPower;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
