package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtStaticMasterData;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class HeaterMode implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String modCd;
	private String label;

	/** {@inheritDoc} */
	@Override
	public UID<HeaterMode> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String modCd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public String getModCd() {
		return modCd;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param modCd String <b>Obligatoire</b>
	 */
	public void setModCd(final String modCd) {
		this.modCd = modCd;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nom'.
	 * @return String label
	 */
	@Field(smartType = "STyLabel", label = "Nom")
	@io.vertigo.datamodel.structure.stereotype.SortField
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nom'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
