package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class HeaterInfo implements DtObject {
	private static final long serialVersionUID = 1L;

	private Double temperature;
	private Double humidity;
	private String mode;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Température'.
	 * @return Double temperature
	 */
	@Field(smartType = "STyDouble", label = "Température")
	public Double getTemperature() {
		return temperature;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Température'.
	 * @param temperature Double
	 */
	public void setTemperature(final Double temperature) {
		this.temperature = temperature;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Humidité'.
	 * @return Double humidity
	 */
	@Field(smartType = "STyDouble", label = "Humidité")
	public Double getHumidity() {
		return humidity;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Humidité'.
	 * @param humidity Double
	 */
	public void setHumidity(final Double humidity) {
		this.humidity = humidity;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String mode
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getMode() {
		return mode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param mode String
	 */
	public void setMode(final String mode) {
		this.mode = mode;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
