package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class HeatersByMode implements DtObject {
	private static final long serialVersionUID = 1L;

	private String mode;
	private Integer count;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String mode
	 */
	@Field(smartType = "STyLabel", label = "Id")
	public String getMode() {
		return mode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Id'.
	 * @param mode String
	 */
	public void setMode(final String mode) {
		this.mode = mode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nombre'.
	 * @return Integer count
	 */
	@Field(smartType = "STyNumber", label = "Nombre")
	public Integer getCount() {
		return count;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nombre'.
	 * @param count Integer
	 */
	public void setCount(final Integer count) {
		this.count = count;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
