package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class WeatherInfo implements DtObject {
	private static final long serialVersionUID = 1L;

	private Double temperature;
	private Double humidity;
	private String location;
	private String icon;
	private String description;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Temperature'.
	 * @return Double temperature
	 */
	@Field(smartType = "STyDouble", label = "Temperature")
	public Double getTemperature() {
		return temperature;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Temperature'.
	 * @param temperature Double
	 */
	public void setTemperature(final Double temperature) {
		this.temperature = temperature;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Humidité'.
	 * @return Double humidity
	 */
	@Field(smartType = "STyDouble", label = "Humidité")
	public Double getHumidity() {
		return humidity;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Humidité'.
	 * @param humidity Double
	 */
	public void setHumidity(final Double humidity) {
		this.humidity = humidity;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String location
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getLocation() {
		return location;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param location String
	 */
	public void setLocation(final String location) {
		this.location = location;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String icon
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getIcon() {
		return icon;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param icon String
	 */
	public void setIcon(final String icon) {
		this.icon = icon;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mode'.
	 * @return String description
	 */
	@Field(smartType = "STyLabel", label = "Mode")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mode'.
	 * @param description String
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
