package com.mlaroche.smartheater.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class WeeklyCalendar implements Entity {
	private static final long serialVersionUID = 1L;

	private Long wcaId;
	private String name;
	private String jsonValue;

	/** {@inheritDoc} */
	@Override
	public UID<WeeklyCalendar> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long wcaId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getWcaId() {
		return wcaId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param wcaId Long <b>Obligatoire</b>
	 */
	public void setWcaId(final Long wcaId) {
		this.wcaId = wcaId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nom'.
	 * @return String name
	 */
	@Field(smartType = "STyLabel", label = "Nom")
	@io.vertigo.datamodel.structure.stereotype.SortField
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nom'.
	 * @param name String
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Value as json'.
	 * @return String jsonValue
	 */
	@Field(smartType = "STyText", label = "Value as json")
	public String getJsonValue() {
		return jsonValue;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Value as json'.
	 * @param jsonValue String
	 */
	public void setJsonValue(final String jsonValue) {
		this.jsonValue = jsonValue;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
